version: '2.0'
services:
 influxdb:
  image: influxdb:latest
  container_name: influxdb
  environment:
    - ADMIN_USER=analytics_engine
    - INFLUX_INIT_PWD=analytics_engine
    - PRE_CREATE_DB=analytics_engine_development
  volumes:
    # Data persistency
    - /srv/docker/influxdb/data:/var/lib/influxdb

 analytics_engine:
  image: analytics_engine:1.9
  container_name: analytics_engine
  build: .

  expose:
   - "46020"
  ports:
   - "46020:46020"
  depends_on:
   - influxdb
  network_mode: "host"

