version: '3'
services:
  influxdb-analytics:
    image: influxdb:latest
    environment:
      - ADMIN_USER=analytics_engine
      - INFLUX_INIT_PWD=analytics_engine
      - PRE_CREATE_DB=analytics_engine_development
    volumes:
      # Data persistency
      - influx-analytics:/var/lib/influxdb
  analytics_engine:
    build: .
    expose:
      - "46020"
    depends_on:
      - influxdb-analytics
    volumes:
      - ./analytics_engine.conf:/analytics_engine/analytics_engine.conf
      
volumes:
  influx-analytics: {}


